from pydantic import BaseModel
from typing import Optional

class ChatRequest(BaseModel):
    """
    A model representing the incoming payload from the API Gateway or frontend.
    It contains the user's prompt, the specific LLM model to be used for generation, 
    and an optional system prompt to define the agent's behavior and instructions.
    """
    message: str
    model: str
    system_prompt: Optional[str] = None

class ChatResponse(BaseModel):
    """
    The main response model for the LLM generation endpoint.
    It returns the final text generated by the local language model.
    """
    reply: str