from pydantic import BaseModel

class ChatRequest(BaseModel):
    """
    A model representing the incoming payload from the API Gateway or frontend.
    It contains the user's prompt and the specific LLM model to be used for generation.
    """
    message: str
    model: str

class ChatResponse(BaseModel):
    """
    The main response model for the LLM generation endpoint.
    It returns the final text generated by the local language model.
    """
    reply: str