import requests

def generate_from_ollama(model_name: str, prompt: str) -> str:
    """
    Sends the prompt to the local Ollama API and retrieves the generated text.
    
    Args:
        model_name (str): The name of the LLM to use (e.g., "phi3", "llama3.1").
        prompt (str): The user's input message.
        
    Returns:
        str: The text generated by the model.
        
    Raises:
        Exception: If the connection to Ollama fails or returns an error.
    """
    # ollama_url = "http://localhost:11434/api/generate"
    ollama_url = "http://host.docker.internal:11434/api/generate"
    
    payload = {
        "model": model_name,
        "prompt": prompt,
        "stream": False
    }
    
    # Make the HTTP request to the local Ollama instance
    response = requests.post(ollama_url, json=payload)
    
    # Raise an exception if the HTTP request returned an error status code
    response.raise_for_status() 
    
    # Parse the JSON response and extract the generated text
    data = response.json()
    return data.get("response", "")
